### ISSUE TITLE
Feature request: Make an example app and package with typescripted svelte version

### ISSUE THREAD

**Issue by gyurielf** [oneezy/monorepo#3]
It would be nice for a lot of people like me who like to use typescript.

**Comment by oneezy** [comment]
I actually attempted to do that in the beginning but ended up with a number of different issues with `ts` so we opted out of it for this starter project. I don't think it's a bad idea though it just ended up being troublesome for us.

Could possibly create a separate branch and make it fully blown typescript or make a separate repo altogether

**Comment by gyurielf** [comment]
I see. Thanks for the quick answer!

**Comment by magick93** [comment]
Do you remember what the issues with adding Typescript were?
