### ISSUE TITLE
Symlink routes aren't working

### ISSUE THREAD

**Issue by oneezy** [oneezy/monorepo#5]
A new bug was introduced in `1.0.0-next.432` of SvelteKit 

See SvelteKit [Issue #6303](https://github.com/sveltejs/kit/issues/6303)

### Reproduction

**1.0.0-next.432** (broke)
❌ https://github.com/oneezy/sveltekit-symlink-repro-next-432

**1.0.0-next.431** (working)
✅ https://github.com/oneezy/sveltekit-symlink-repro-next-431

---

![image](https://user-images.githubusercontent.com/7369575/186837092-952bfe1b-e8d9-47bf-9298-bd037cb041f0.png)

**Comment by myhrmans** [comment]
Is this what is causing also the icons and different things not to load properly when only starting the docs app?

**Comment by oneezy** [comment]
yes i believe so @myhrmans , that's why some of the icons/ images won't work when only running one app at a time
i.e.
```
pnpm dev --filter @apps/docs
```
this monorepo only uses one folder for `static` assets which is located at `./apps/site/static` so in order to get images working in all apps you'd need to symlink that static folder into every new app that's added to the `apps/*` folder.

I added a section in the `README` that explains [where and when to use symlinks](https://github.com/oneezy/monorepo#add-app) if you'd like to check it out.

---

unfortunately none of that will work until [sveltekit issue #6303](https://github.com/sveltejs/kit/issues/6303) is resolved.

**Comment by oneezy** [comment]
This is fixed
